package com.intermarche.fidelity.imports;

import com.intermarche.fidelity.domain.AccountStatus;
import com.intermarche.fidelity.domain.FidelityAccount;
import com.intermarche.fidelity.domain.FidelityProgramSetting;
import io.quarkus.hibernate.orm.panache.Panache;
import io.smallrye.common.annotation.RunOnVirtualThread;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import java.io.InputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Bulk CSV import of loyalty accounts / cards (§14, §18, §33.1).
 * <p>
 * The card number is the account's only key (imfid is pseudonymous, §33.3). When
 * the first column is blank the number is generated by imfid as a 13-digit EAN-13
 * opened by the reserved program prefix (§33.1) — a sequence plus a check digit,
 * never keyed in; when it is provided the row is matched on it (a re-import
 * updates the same account). Initial balances are never set here: they arrive as
 * {@code ADJUSTMENT} movements (§32.1), so {@code balance} is left untouched.
 * <p>
 * Consumed columns (resolved by header name; unknown columns of the shared
 * feed are ignored): CARD_NUMBER (key), STATUS, ACTIVATED_AT, LAST_USED_AT,
 * TRANSFERRED_TO_CARD, dates in
 * ISO local date-time; a blank {@code STATUS} defaults to {@code ACTIVE} (§30.4).
 * The {@code fid-admin} role guard (§24.1) is attached in the security build step.
 */
@Path("/fidelity/accounts/import")
@ApplicationScoped
@RunOnVirtualThread
public class FidelityAccountCsvResource extends ImporterCsvResource {

    /** Header name of the natural key: the card number (blank = generate, §33.1). */
    static final String COL_CARD_NUMBER = "CARD_NUMBER";
    /** Header name of the account status. */
    static final String COL_STATUS = "STATUS";
    /** Header name of the activation instant. */
    static final String COL_ACTIVATED_AT = "ACTIVATED_AT";
    /** Header name of the last-use instant. */
    static final String COL_LAST_USED_AT = "LAST_USED_AT";
    /** Header name of the successor card of a transferred account. */
    static final String COL_TRANSFERRED_TO_CARD = "TRANSFERRED_TO_CARD";

    /** The columns this importer cannot work without. */
    private static final List<String> REQUIRED_COLUMNS = List.of(
            COL_STATUS, COL_ACTIVATED_AT, COL_LAST_USED_AT, COL_TRANSFERRED_TO_CARD);

    /**
     * Total length of a card number (§33.1): a 13-digit EAN-13.
     */
    private static final int CARD_LENGTH = 13;

    /**
     * Default reserved card-number prefix used until the {@code card.prefix}
     * program setting is seeded (§25.1, §33.1); a GS1 restricted-circulation range
     * kept out of the product EAN ranges.
     */
    private static final String DEFAULT_CARD_PREFIX = "29";

    /**
     * Imports or updates loyalty accounts from a CSV stream (§18).
     *
     * @param inputStream The account CSV stream.
     * @return The JSON import report (created/updated counts and errors).
     */
    @POST
    @Consumes({MediaType.TEXT_PLAIN, MediaType.APPLICATION_OCTET_STREAM})
    @Produces(MediaType.APPLICATION_JSON)
    public Response importAccounts(InputStream inputStream) {
        return this.importCsvStream(inputStream, COL_CARD_NUMBER, REQUIRED_COLUMNS);
    }

    /**
     * Accepts empty-key rows: a blank {@code CARD_NUMBER} cell is this import's
     * "generate the card number" instruction (§33.1), so such rows must reach
     * {@link #processLineLogic} instead of being dropped by the base importer.
     *
     * @return Always true for the account import.
     */
    @Override
    protected boolean acceptsEmptyKey() {
        return true;
    }

    /**
     * Bulk-fetches the accounts already present for the chunk, keyed by card number;
     * blank keys (cards to generate) match nothing.
     *
     * @param parsedLines The rows of the current chunk.
     * @param targetCards The distinct card numbers present in the chunk.
     * @param counters    The global {@code [created, updated]} counters.
     * @param errors      The accumulating list of definitive row errors.
     * @return A map of card number to existing {@link FidelityAccount}, never null.
     */
    @Override
    protected Map<String, Object> processChunkWithFallback(List<LineData> parsedLines, Set<String> targetCards, int[] counters, List<String> errors) {
        Map<String, Object> contextMap = new HashMap<>();
        if (!parsedLines.isEmpty() && !targetCards.isEmpty()) {
            for (FidelityAccount account : FidelityAccount.<FidelityAccount>list("cardNumber in ?1", targetCards)) {
                contextMap.put(account.cardNumber, account);
            }
        }
        return contextMap;
    }

    /**
     * Creates an account (generating the card number when the row's key is blank)
     * or updates an existing one when one of its imported fields changed.
     *
     * @param data      The row to process.
     * @param entityMap A map of card number to existing {@link FidelityAccount}.
     * @param counters  The local {@code [created, updated]} counters to increment.
     */
    @Override
    protected void processLineLogic(LineData data, Map<String, Object> entityMap, int[] counters) {
        FidelityAccount account = data.code.isEmpty() ? null : (FidelityAccount) entityMap.get(data.code);
        if (account == null) {
            account = new FidelityAccount();
            account.cardNumber = data.code.isEmpty() ? generateCardNumber() : data.code;
            feedAccount(data, account);
            counters[0]++;
            Panache.getEntityManager().persist(account);
        } else if (hasChanged(data, account)) {
            account = FidelityAccount.findById(account.id);
            feedAccount(data, account);
            counters[1]++;
        }
    }

    /**
     * Looks up an account by card number for the 1-by-1 fallback; a blank key
     * (card to generate) resolves to null so the row becomes a creation.
     *
     * @param data The row to look up.
     * @return The {@link FidelityAccount}, or null when absent or to be generated.
     */
    @Override
    protected Object findEntityForLine(LineData data) {
        return data.code.isEmpty() ? null : FidelityAccount.findByCardNumber(data.code);
    }

    /**
     * Populates an account's imported fields from a parsed row; {@code balance}
     * stays as is (seeded balances arrive as {@code ADJUSTMENT} movements, §32.1).
     *
     * @param data    The row carrying the values.
     * @param account The account to populate.
     */
    private void feedAccount(LineData data, FidelityAccount account) {
        AccountStatus status = safeParseEnum(AccountStatus.class, data, COL_STATUS);
        account.status = status != null ? status : AccountStatus.ACTIVE;
        account.activatedAt = safeParseDateTime(data, COL_ACTIVATED_AT);
        account.lastUsedAt = safeParseDateTime(data, COL_LAST_USED_AT);
        account.transferredToCard = safeGetNonBlank(data, COL_TRANSFERRED_TO_CARD);
    }

    /**
     * Tells whether any of the account's imported fields differs from the row, so
     * an unchanged account is left untouched (the checksum can't be used here as it
     * folds in {@code balance}, which this import never carries).
     *
     * @param data    The row carrying the incoming values.
     * @param account The persisted account.
     * @return true when the account must be updated.
     */
    private boolean hasChanged(LineData data, FidelityAccount account) {
        AccountStatus status = safeParseEnum(AccountStatus.class, data, COL_STATUS);
        AccountStatus incomingStatus = status != null ? status : AccountStatus.ACTIVE;
        return account.status != incomingStatus
                || !Objects.equals(account.activatedAt, safeParseDateTime(data, COL_ACTIVATED_AT))
                || !Objects.equals(account.lastUsedAt, safeParseDateTime(data, COL_LAST_USED_AT))
                || !Objects.equals(account.transferredToCard, safeGetNonBlank(data, COL_TRANSFERRED_TO_CARD));
    }

    // --------------------------------------------------
    // Card number generation (§33.1)
    // --------------------------------------------------

    /**
     * Generates a fresh 13-digit EAN-13 card number opened by the reserved program
     * prefix (§33.1): the prefix, a left-padded sequence and a trailing check digit.
     * The sequence starts past the current account count and advances until the
     * candidate is free — auto-flush makes rows persisted earlier in the same
     * transaction visible to the uniqueness probe.
     *
     * @return A unique 13-digit card number.
     */
    private String generateCardNumber() {
        String prefix = FidelityProgramSetting.getString(FidelityProgramSetting.KEY_CARD_PREFIX, DEFAULT_CARD_PREFIX);
        long sequence = FidelityAccount.count() + 1;
        while (true) {
            String body = buildBody(prefix, sequence);
            String candidate = body + ean13CheckDigit(body);
            if (FidelityAccount.findByCardNumber(candidate) == null) {
                return candidate;
            }
            sequence++;
        }
    }

    /**
     * Builds the 12-digit body of a card number: the reserved prefix followed by
     * the sequence, left-padded (or truncated to its low digits) to fill the width.
     *
     * @param prefix   The reserved prefix.
     * @param sequence The monotonic sequence value.
     * @return The 12-digit body preceding the check digit.
     */
    private static String buildBody(String prefix, long sequence) {
        int bodyLength = CARD_LENGTH - 1;
        int sequenceWidth = Math.max(1, bodyLength - prefix.length());
        String sequenceDigits = String.format("%0" + sequenceWidth + "d", sequence);
        if (sequenceDigits.length() > sequenceWidth) {
            sequenceDigits = sequenceDigits.substring(sequenceDigits.length() - sequenceWidth);
        }
        String body = prefix + sequenceDigits;
        if (body.length() > bodyLength) {
            body = body.substring(body.length() - bodyLength);
        }
        return body;
    }

    /**
     * Computes the EAN-13 check digit of a 12-digit body: digits are weighted 1 and
     * 3 alternately from the left, and the check completes the sum to a multiple of
     * ten.
     *
     * @param body The 12-digit body.
     * @return The check digit (0-9).
     */
    private static int ean13CheckDigit(String body) {
        int sum = 0;
        for (int i = 0; i < body.length(); i++) {
            int digit = body.charAt(i) - '0';
            sum += (i % 2 == 0) ? digit : digit * 3;
        }
        return (10 - (sum % 10)) % 10;
    }
}
