package com.intermarche.fidelity.domain;

import io.quarkus.panache.common.Page;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

/**
 * A loyalty account, keyed by the physical card number (§14).
 * <p>
 * The {@link #balance} is the signed sum of the account's movements,
 * denormalized here for read access; the movements remain the single source of
 * truth (§14). Every write touching an account is serialized under a per-card
 * lock ({@code SELECT FOR UPDATE}, §30.1). There is never any auto-creation: an
 * unknown card yields an empty earn (§20).
 * <p>
 * imfid is pseudonymous — the card number is the only key, no nominative data
 * anywhere (§33.3).
 * <p>
 * Fields are public to comply with Quarkus/Panache conventions.
 */
@Entity
@Table(name = "fidelity_accounts",
        indexes = {
                @Index(name = "idx_account_card", columnList = "card_number"),
                @Index(name = "idx_account_status", columnList = "status"),
                @Index(name = "idx_account_last_used", columnList = "last_used_at")
        }
)
public class FidelityAccount extends BaseEntity {

    /**
     * The card number: 13 digits opened by a reserved prefix, equal to the POS
     * contract {@code customerCode}; generated by imfid, never keyed in (§14, §33.1).
     */
    @Column(name = "card_number", unique = true, nullable = false, length = 40)
    @NotBlank(message = "Card number is mandatory")
    public String cardNumber;

    /**
     * The account status governing whether it earns and/or burns (§25.3, §30.4).
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @NotNull(message = "Account status is mandatory")
    public AccountStatus status = AccountStatus.ACTIVE;

    /**
     * When the account was activated (CGU activation within two months); null while
     * still PENDING_ACTIVATION (§25.3).
     */
    @Column(name = "activated_at")
    public LocalDateTime activatedAt;

    /**
     * The last fiscal use of the card; drives the 24-month purge batch (§14, §16).
     */
    @Column(name = "last_used_at")
    public LocalDateTime lastUsedAt;

    /**
     * The materialized balance, derivable from the movements and denormalized for
     * read access; euro at scale 2 (§30.5). A negative balance is tolerated (I7).
     */
    @Column(nullable = false, precision = 19, scale = 2)
    public BigDecimal balance = BigDecimal.ZERO.setScale(2, RoundingMode.HALF_UP);

    /**
     * The card number the balance was transferred to on loss/theft; null on a live
     * account. The number in place is never modified — a new account is created and
     * this points to it, forming the transfer chain resolved at ingestion (§16, §32.2).
     */
    @Column(name = "transferred_to_card", length = 40)
    public String transferredToCard;

    // --------------------------------------------------
    // Domain helpers
    // --------------------------------------------------

    /**
     * Indicates whether the account may accrue loyalty: ACTIVE, or
     * PENDING_ACTIVATION which accrues but cannot burn (§25.3). A RESILIATED
     * account never earns.
     *
     * @return true when the account can earn.
     */
    public boolean canEarn() {
        return status == AccountStatus.ACTIVE || status == AccountStatus.PENDING_ACTIVATION;
    }

    /**
     * Indicates whether the account may burn: only a fully ACTIVE account can
     * (§25.3).
     *
     * @return true when the account can burn.
     */
    public boolean canBurn() {
        return status == AccountStatus.ACTIVE;
    }

    /**
     * Indicates whether the balance was transferred away on loss/theft.
     *
     * @return true when a successor card is set.
     */
    public boolean isTransferred() {
        return transferredToCard != null && !transferredToCard.isBlank();
    }

    // --------------------------------------------------
    // Panache Active Record Queries
    // --------------------------------------------------

    /**
     * Finds an account by its card number.
     *
     * @param cardNumber The card number.
     * @return The account, or null if none matches.
     */
    public static FidelityAccount findByCardNumber(String cardNumber) {
        return find("cardNumber", cardNumber).firstResult();
    }

    /**
     * Finds an account by its card number under a pessimistic write lock
     * ({@code SELECT FOR UPDATE}) — the database pendant of the burn lease and the
     * material condition of the "one active reservation per card" (I11) and
     * "the second recalc sees the first credit" invariants (§26.1, §30.1). Must be
     * called within a transaction; every write touching an account takes this lock.
     *
     * @param cardNumber The card number.
     * @return The locked account, or null if none matches.
     */
    public static FidelityAccount lockByCardNumber(String cardNumber) {
        return find("cardNumber", cardNumber)
                .withLock(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE)
                .firstResult();
    }

    /**
     * Resolves the live account at the end of the transfer chain starting from the
     * given card (§32.2): follows {@link #transferredToCard} until a live account,
     * a missing successor or a cycle guard is reached.
     *
     * @param cardNumber The card number to start from.
     * @return The live successor account, the resiliated tail when there is no live
     *         successor, or null when the starting card is unknown.
     */
    public static FidelityAccount resolveActive(String cardNumber) {
        FidelityAccount account = findByCardNumber(cardNumber);
        int guard = 0;
        while (account != null && account.isTransferred() && guard++ < 100) {
            FidelityAccount next = findByCardNumber(account.transferredToCard);
            if (next == null) {
                break;
            }
            account = next;
        }
        return account;
    }

    /**
     * Lists accounts unused since the given threshold, candidates for the 24-month
     * purge batch (§16).
     *
     * @param threshold The cut-off instant; accounts last used before it are returned.
     * @return The stale accounts, never null.
     */
    public static List<FidelityAccount> listUnusedSince(LocalDateTime threshold) {
        return list("status <> ?1 and coalesce(lastUsedAt, createdAt) < ?2",
                AccountStatus.RESILIATED, threshold);
    }

    /**
     * Returns a page of accounts ordered by card number.
     *
     * @param pageIndex Zero-based page index.
     * @param pageSize  Page size.
     * @return The requested page of accounts, never null.
     */
    public static List<FidelityAccount> page(int pageIndex, int pageSize) {
        return find("order by cardNumber").page(Page.of(pageIndex, pageSize)).list();
    }

    // --------------------------------------------------
    // Checksum
    // --------------------------------------------------

    /**
     * Calculates a checksum from the account's business fields.
     *
     * @return Checksum integer value.
     */
    @Override
    public int getChecksum() {
        return Objects.hash(cardNumber, status, activatedAt, lastUsedAt, balance, transferredToCard);
    }
}
