package com.intermarche.fidelity.domain.util;

import com.intermarche.fidelity.domain.FidelityAccount;
import com.intermarche.fidelity.domain.FidelityProgramSetting;
import jakarta.enterprise.context.ApplicationScoped;

/**
 * Generates loyalty card numbers (§33.1): 13 digits opened by a reserved prefix (a
 * program setting, {@link FidelityProgramSetting#KEY_CARD_PREFIX}, outside the product
 * EAN ranges), a sequence, and an EAN-13 check digit as the last digit. The number is
 * generated by imfid at creation, never keyed in — only restituted, and shown as a
 * printable EAN-13 barcode on the card sheet (§33.1).
 * <p>
 * The prefix is the scan discriminant that lets the register tell a card from a product
 * (Annexe A).
 */
@ApplicationScoped
public class CardNumberGenerator {

    /**
     * The default reserved prefix when the setting is absent — {@code 299}, outside the
     * usual product EAN ranges (§33.1).
     */
    private static final String DEFAULT_PREFIX = "299";

    /**
     * Generates the next unused 13-digit card number (§33.1).
     * <p>
     * The 12 leading digits are the reserved prefix followed by a zero-padded sequence;
     * the 13th is the EAN-13 check digit. The sequence walks forward until an unused
     * number is found, so a collision on a re-seeded database never yields a duplicate.
     *
     * @return A fresh, unused 13-digit card number.
     */
    public String generate() {
        String prefix = digitsOnly(FidelityProgramSetting.getString(
                FidelityProgramSetting.KEY_CARD_PREFIX, DEFAULT_PREFIX), DEFAULT_PREFIX);
        long sequence = FidelityAccount.count() + 1;
        for (int attempt = 0; attempt < 1_000_000; attempt++) {
            String base12 = base12(prefix, sequence + attempt);
            String candidate = base12 + checkDigit(base12);
            if (FidelityAccount.findByCardNumber(candidate) == null) {
                return candidate;
            }
        }
        throw new IllegalStateException("Unable to generate a free card number");
    }

    /**
     * Builds the 12 leading digits: the prefix followed by the sequence, zero-padded and
     * right-truncated to 12 digits.
     * <p>
     * When the guard falls through, the padded body is exactly 12 digits by
     * construction: the guard guarantees {@code prefix.length() + seq.length() <= 12},
     * so the zero fill completes the length to precisely 12 — no final clamp is needed.
     *
     * @param prefix   The reserved prefix (digits only).
     * @param sequence The sequence number.
     * @return The 12-digit base.
     */
    private String base12(String prefix, long sequence) {
        String body = prefix + sequence;
        if (body.length() > 12) {
            return body.substring(body.length() - 12);
        }
        StringBuilder padded = new StringBuilder(prefix);
        String seq = Long.toString(sequence);
        int fill = 12 - prefix.length() - seq.length();
        for (int i = 0; i < fill; i++) {
            padded.append('0');
        }
        padded.append(seq);
        return padded.toString();
    }

    /**
     * Computes the EAN-13 check digit of a 12-digit base (§33.1).
     *
     * @param base12 The 12-digit base.
     * @return The check digit as a single-character string.
     */
    private String checkDigit(String base12) {
        int sum = 0;
        for (int i = 0; i < base12.length(); i++) {
            int digit = base12.charAt(i) - '0';
            sum += (i % 2 == 0) ? digit : digit * 3;
        }
        int check = (10 - (sum % 10)) % 10;
        return Integer.toString(check);
    }

    /**
     * Keeps only the digits of a candidate prefix, falling back when none remain (§31.2).
     *
     * @param value    The configured prefix.
     * @param fallback The fallback prefix.
     * @return A digits-only prefix.
     */
    private static String digitsOnly(String value, String fallback) {
        if (value == null) {
            return fallback;
        }
        String digits = value.replaceAll("\\D", "");
        return digits.isEmpty() ? fallback : digits;
    }
}
